### ISSUE TITLE
Issues when installing on Mac

### ISSUE THREAD

**Issue by simonexmachina** [XertroV/nvbclient#8]
The README refers to running `initialize_nvb_client_db` but this doesn't appear to be created when I install on Mac.

**Comment by simonexmachina** [comment]
Also when I run `pserve development.ini` I get the following output:

```
Traceback (most recent call last):
  File "/usr/local/bin/pserve", line 9, in <module>
    load_entry_point('pyramid', 'console_scripts', 'pserve')()
  File "/usr/local/lib/python3.5/site-packages/pyramid-1.7-py3.5.egg/pyramid/scripts/pserve.py", line 60, in main
    return command.run()
  File "/usr/local/lib/python3.5/site-packages/pyramid-1.7-py3.5.egg/pyramid/scripts/pserve.py", line 371, in run
    global_conf=vars)
  File "/usr/local/lib/python3.5/site-packages/pyramid-1.7-py3.5.egg/pyramid/scripts/pserve.py", line 406, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/usr/local/lib/python3.5/site-packages/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python3.5/site-packages/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python3.5/site-packages/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python3.5/site-packages/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python3.5/site-packages/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/simonwade/dev/Workspace/nvbclient/nvbclient/__init__.py", line 29, in main
    config.scan()
  File "/usr/local/lib/python3.5/site-packages/pyramid-1.7-py3.5.egg/pyramid/config/__init__.py", line 976, in scan
    ignore=ignore)
  File "/usr/local/lib/python3.5/site-packages/venusian-1.0-py3.5.egg/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/Users/simonwade/dev/Workspace/nvbclient/nvbclient/bitcoin.py", line 8, in <module>
    from pycoin.services.blockchain_info import spendables_for_address, send_tx
ImportError: cannot import name 'spendables_for_address'
```

**Comment by XertroV** [comment]
Hey @aexmachina - this isn't really supported anymore, so I'm not going to issue a fix. 

It looks like the services part of pycoin has been refactored into a class, so if you checkout d9be86023ad134d3479adf5147d2b64910a3d77d in pycoin and install that it might work.

Unsure about `initialize_nvb_client_db` - that's an automagic pyramids thing. Here's the function it calls though: https://github.com/XertroV/nvbclient/blob/master/nvbclient/scripts/initializedb.py#L37

**Comment by simonexmachina** [comment]
That's cool, just curious. Thanks.
